"""added credentials column to user table

Revision ID: 80232966236d
Revises: a44a1f349a57
Create Date: 2022-03-15 08:52:25.768160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80232966236d'
down_revision = 'a44a1f349a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credentials', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credentials')
    # ### end Alembic commands ###
